#pragma once
#include <string>

namespace mediasoup
{

enum class WorkerLogLevel {
    WL_DEBUG,
    WL_WARN,
    WL_ERROR,
    WL_NONE
};

struct WorkerSettings {
	/**
     * Logging level for logs generated by the media worker subprocesses (check
	 * the Debugging documentation). Valid values are 'debug', 'warn', 'error' and
	 * 'none'. Default 'error'.
	 */
    WorkerLogLevel logLevel = WorkerLogLevel::WL_ERROR;

	/**
	 * Log tags for debugging. Check the list of available tags in Debugging
	 * documentation.
	 */
	std::string logTags;
 
	/**
	 * Minimun RTC port for ICE, DTLS, RTP, etc. Default 10000.
	 */
	int rtcMinPort = 10000;

	/**
	 * Maximum RTC port for ICE, DTLS, RTP, etc. Default 59999.
	 */
	int rtcMaxPort = 59999;

	/**
	 * Path to the DTLS public certificate file in PEM format. If unset, a
	 * certificate is dynamically created.
	 */
	std::string dtlsCertificateFile;

	/**
	 * Path to the DTLS certificate private key file in PEM format. If unset, a
	 * certificate is dynamically created.
	 */
	std::string dtlsPrivateKeyFile;

	/**
	 * Custom application data.
	 */
	void* appData;
};

class IWorker {
public:
	virtual ~IWorker() {}
};

}